<?php
/*
* Copyright 2016 Compropago.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
/**
 * @author Rolando Lucio <rolando@compropago.com>
 */
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()) ?>" style="display:none">
    <?php if ($block->getMethod()->getPayableTo()): ?>
        <label class="label"><span><?php echo $block->escapeHtml(__('Make Check payable to:')) ?></span></label> <?php echo $block->escapeHtml($block->getMethod()->getProviders()) ?>
    <?php endif; ?>
    <?php if ($block->getMethod()->getMailingAddress()): ?>
        <div class="admin__field">
            <label class="admin__field-label"><span><?php echo $block->escapeHtml(__('Send Check to:')) ?></span></label>
            <div class="admin__field-control checkmo-mailing-address">
                <?php /* @noEscape */ echo nl2br($block->escapeHtml($block->getMethod()->getProviders())) ?>
            </div>
        </div>
    <?php endif; ?>
</fieldset>
