<div id="compropagoWrapper">
    <?php
        $compropago_id = $block->getVars();
        if (!empty($compropago_id)) {
    ?>

    <div id="compropagoWrapper">
        <div class="compropagoDivFrame" id="compropagodContainer" style="width: 100%;">
            <iframe style="width: 100%;"
                    id="compropagodFrame"
                    src="https://www.compropago.com/comprobante/?confirmation_id=<?php echo $compropago_id; ?>"
                    frameborder="0" scrolling="yes"> </iframe>
        </div>

        <script type="text/javascript">
            function resizeIframe() {
                var container=document.getElementById("compropagodContainer");
                var iframe=document.getElementById("compropagodFrame");
                if(iframe && container){
                    var ratio=585/811;
                    var width=container.offsetWidth;
                    var height=(width/ratio);
                    if(height>760){ height=760; }
                    iframe.style.width=width + 'px';
                    iframe.style.height=height + 'px';
                }
            }

            window.onload = function() {
                resizeIframe();
            };
            window.onresize = function() {
                resizeIframe();
            };
        </script>
    </div>

    <?php } ?>
</div>

