<?php
/*
* Copyright 2016 Compropago.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
/**
 * @author Rolando Lucio <rolando@compropago.com>
 */
?>
esta firn de que es?
<?php if ($block->getMethod()->getMailingAddress() || $block->getMethod()->getPayableTo()): ?>
    <dl class="items check payable" id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()) ?>" style="display:none;">
        <?php if ($block->getMethod()->getPayableTo()): ?>
            <dt class="title"><?php echo $block->escapeHtml(__('Make Check payable to:')) ?></dt>
            <dd class="content"><?php echo $block->escapeHtml($block->getMethod()->getPayableTo()) ?></dd>
        <?php endif; ?>
        <?php if ($block->getMethod()->getMailingAddress()): ?>
            <dt class="title"><?php echo $block->escapeHtml(__('Send Check to:')) ?></dt>
            <dd class="content">
                <address class="checkmo mailing address">
                    <?php /* @noEscape */ echo nl2br($block->escapeHtml($block->getMethod()->getMailingAddress())) ?>
                </address>
            </dd>
        <?php endif; ?>
    </dl>
<?php endif; ?>
